
version: '3.8'

services:
  app:
    image: learning-platform-web
    build: 
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - SECRET=development
      - NEXTAUTH_URL=http://localhost:3000/api/auth
      - MONGODB_URI=mongodb://user:pass@db:27017
    env_file:
      - ./.env.local
  
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb-data:/data/db
    
volumes:
  mongodb-data: